services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - 54327:5432
    environment:
      - POSTGRES_PASSWORD=lek1234
      - POSTGRES_USER=pornlert
      - POSTGRES_DB=pornlert

  admin:
    image: dpage/pgadmin4:9.16
    container_name: 69-s3-admin
    ports:
      - 8083:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pornlert-p@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=lek1234

  app:
    image: prawee/strapi
    container_name: 69-s3-app
    ports:
      - 8080:1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=pornlert
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=pornlert
      - DATABASE_PASSWORD=lek1234
